:fusor:
  :content:
    :content_view:
      :composite_view_name: "Fusor Deployment"
      :rpm_component_view_name: "Fusor RPM Content"
      :puppet_component_view_name: "Fusor Puppet Content"

    # NOTE: product_name and repository_set_name are provided only for
    # convencience / display purposes. All repository finding should be
    # driven off of product_id / repository_set_id, as those are the only
    # things guaranteed not to change.
    :rhevm:
      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "168"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "1952"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "6.7"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "4185"
        :repository_set_name: "Red Hat Satellite Tools 6.1 (for RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "1673"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :product_id: "150"
        :repository_set_id: "3790"
        :repository_set_name: "Red Hat Enterprise Virtualization Manager 3.5 (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "JBoss Enterprise Application Platform"
        :product_id: "183"
        :repository_set_id: "1559"
        :repository_set_name: "JBoss Enterprise Application Platform 6 (RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

    :rhevh:
      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "168"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "1952"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "6.7"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "4185"
        :repository_set_name: "Red Hat Satellite Tools 6.1 (for RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"

      - :product_name: "Red Hat Enterprise Virtualization"
        :product_id: "150"
        :repository_set_id: "1099"
        :repository_set_name: "Red Hat Enterprise Virtualization Management Agents (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

    :cloudforms:
      - :product_name: "Red Hat CloudForms Beta"
        :product_id: "303"
        :repository_set_id: "4635"
        :repository_set_name: "Red Hat CloudForms Beta (Files)"
        :basearch: "x86_64"
        #:image_file_name: "cfme-rhevm-5.3-54.x86_64.rhevm.ova" # Default behavior uses the 'latest' image file.

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "2455"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "7.1"
        #Need Red Hat 7.1 Operating Sysetem setup including Media, architecture, and other associations.

    :openstack:
      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "2456"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "2455"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "7.1"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "3030"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
        :basearch: "x86_64"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "2463"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :product_id: "69"
        :repository_set_id: "2472"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat OpenStack"
        :product_id: "191"
        :repository_set_id: "4492"
        :repository_set_name: "Red Hat Enterprise Linux OpenStack Platform 7.0 for RHEL 7 (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat OpenStack"
        :product_id: "191"
        :repository_set_id: "4495"
        :repository_set_name: "Red Hat Enterprise Linux OpenStack Platform 7.0 director for RHEL 7 (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat OpenStack"
        :product_id: "191"
        :repository_set_id: "4497"
        :repository_set_name: "Red Hat Enterprise Linux OpenStack Platform 7.0 for RHEL 7 (Files)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat Software Collections for RHEL Server"
        :product_id: "201"
        :repository_set_id: "2808"
        :repository_set_name: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server"
        :basearch: "x86_64"
        :releasever: "7Server"

  :puppet_classes:
    - :name: "ovirt"
    - :name: "ovirt::engine::config"
    - :name: "ovirt::engine::packages"
    - :name: "ovirt::engine::setup"
    - :name: "ovirt::engine::import_template"
    - :name: "ovirt::engine::run_vm"
    - :name: "ovirt::hypervisor::packages"

  :host_groups:
    :rhev:
     :root_name: "Fusor Base" # seeded by the fusor-installer
     :host_groups:
       - :parent: "Fusor Base"

       - :name: "RHEV-Engine"
         :os: "RedHat"
         :major: "6"
         :minor: "7"
         :parent: :root_deployment
         :puppet_classes:
           - :name: "ovirt"
             :parameters:
             - :name: "product"
               :override: "RHEV"
           - :name: "ovirt::engine::config"
           - :name: "ovirt::engine::packages"
           - :name: "ovirt::engine::setup"
             :parameters:
             - :name: "firewall_manager"
               :override: "iptables"
         :activation_key:
           :name: "RHEV-Engine"
           :content: :rhevm
           :subscription_descriptions:
             - "Red Hat Cloud Infrastructure"

       - :name: "RHEV-Hypervisor"
         :os: "RedHat"
         :major: "6"
         :minor: "7"
         :parent: :root_deployment
         :puppet_classes:
           - :name: "ovirt"
             :parameters:
             - :name: "product"
               :override: "RHEV"
           - :name: "ovirt::hypervisor::packages"
         :activation_key:
           :name: "RHEV-Hypervisor"
           :content: :rhevh
           :subscription_descriptions:
             - "Red Hat Cloud Infrastructure"

    :openstack:
     :root_name: "Fusor Base" # seeded by the fusor-installer
     :host_groups:
       - :parent: "Fusor Base"

       - :name: "OpenStack-Undercloud"
         :parent: :root_deployment
         :os: "RedHat"
         :major: "7"
         :minor: "1"
         :activation_key:
           :name: "OpenStack-Undercloud"
           :content: :openstack
           :subscription_descriptions:
             - "Red Hat Cloud Infrastructure"

